import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Bot, CalendarRange, CheckCircle2, Clock3, Loader2, Radar, ShieldCheck, WandSparkles } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useLocation } from "wouter";
import type { AutomationSetting } from "../../../drizzle/schema";
import AutopilotPanel from "./AutopilotPanel";

type AutomationForm = Omit<Pick<AutomationSetting, "enabled" | "cadence" | "postsPerWeek" | "defaultPublishTime" | "planningHorizonDays" | "requireApproval" | "allowSelfApproval" | "refreshRadarDaily" | "preferredAreas" | "preferredFormats">, "postsPerWeek"> & { postsPerWeek: number | string };

const defaultSettings: AutomationForm = { enabled: false, cadence: "weekdays", postsPerWeek: 5, defaultPublishTime: "18:30", planningHorizonDays: 30, requireApproval: true, allowSelfApproval: true, refreshRadarDaily: true, preferredAreas: "", preferredFormats: "carousel,post,reel" };

export default function AutomationCenter({ settings }: { settings: AutomationSetting | null }) {
  const [, setLocation] = useLocation();
  const [form, setForm] = useState<AutomationForm>(settings ?? defaultSettings);
  const [planDays, setPlanDays] = useState<7 | 15 | 30>(30);
  const [planMessage, setPlanMessage] = useState<string | null>(null);
  const utils = trpc.useUtils();
  const update = trpc.socialStudio.updateAutomation.useMutation({ onSuccess: async data => { setForm(data); await utils.socialStudio.data.invalidate(); } });
  const generateCampaign = trpc.socialCampaign.generate.useMutation({ onSuccess: async result => { setPlanMessage(`${result.count} conteúdos foram criados como rascunhos e distribuídos ao longo do período em America/Sao_Paulo${result.reused ? " (solicitação já processada; sem duplicação)" : ""}.`); await utils.socialStudio.data.invalidate(); }, onError: error => setPlanMessage(error.message) });
  useEffect(() => setForm(settings ?? form), [settings?.id]);
  const submit = (event: FormEvent) => { event.preventDefault(); update.mutate({ ...form, postsPerWeek: Number(form.postsPerWeek), planningHorizonDays: Number(form.planningHorizonDays), preferredAreas: form.preferredAreas || null, preferredFormats: form.preferredFormats || null }); };

  return <div className="studio-automation space-y-5">
    <section className="studio-scheduler-hero"><div className="studio-scheduler-mark"><Bot className="h-5 w-5" /></div><div><p>Automação assistida</p><h1>Cadência, segurança e previsibilidade</h1><span>O sistema organiza rascunhos. A aprovação humana continua obrigatória antes de qualquer envio externo.</span></div><div className="studio-automation-state"><small>Automação</small><Switch checked={Boolean(form.enabled)} onCheckedChange={enabled => setForm({ ...form, enabled })} aria-label="Ativar automação assistida" /><strong>{form.enabled ? "Ativa" : "Pausada"}</strong></div></section>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <form onSubmit={submit} className="studio-light-card studio-automation-form">
        <div className="studio-card-heading"><div><p className="studio-card-kicker">Configuração de cadência</p><h2>Defina o ritmo da operação</h2></div><span className="studio-status-chip">Fuso: São Paulo</span></div>
        <p className="studio-form-intro">As preferências orientam a produção de rascunhos e a agenda. O conteúdo não é publicado automaticamente.</p>
        <div className="mt-6 grid gap-4 md:grid-cols-2"><AutomationField label="Cadência"><select value={form.cadence} onChange={event => setForm({ ...form, cadence: event.target.value as AutomationForm["cadence"] })}><option value="daily">Todos os dias</option><option value="weekdays">Segunda a sexta</option><option value="custom">Personalizada</option></select></AutomationField><AutomationField label="Publicações por semana"><input type="number" min={1} max={7} value={form.postsPerWeek} onChange={event => setForm({ ...form, postsPerWeek: event.target.value })} /></AutomationField><AutomationField label="Horário padrão"><input type="time" value={form.defaultPublishTime} onChange={event => setForm({ ...form, defaultPublishTime: event.target.value })} /></AutomationField><AutomationField label="Horizonte de planejamento"><select value={form.planningHorizonDays} onChange={event => setForm({ ...form, planningHorizonDays: Number(event.target.value) })}><option value={7}>7 dias</option><option value={15}>15 dias</option><option value={30}>30 dias</option><option value={60}>60 dias</option><option value={90}>90 dias</option></select></AutomationField><AutomationField label="Áreas prioritárias" full><input value={form.preferredAreas ?? ""} onChange={event => setForm({ ...form, preferredAreas: event.target.value })} placeholder="Trabalhista, Consumidor, Empresarial..." /></AutomationField><AutomationField label="Formatos preferidos" full><input value={form.preferredFormats ?? ""} onChange={event => setForm({ ...form, preferredFormats: event.target.value })} placeholder="carousel, post, reel" /></AutomationField></div>
        <div className="mt-5 grid gap-2"><PolicyToggle icon={ShieldCheck} title="Aprovação jurídica" text="Sempre obrigatória antes de qualquer publicação" staticOn /><PolicyToggle icon={Radar} title="Priorizar Radar" text={form.refreshRadarDaily ? "Considerar pautas atuais ao atualizar" : "Atualização e pesquisa manuais"} active={form.refreshRadarDaily} onClick={() => setForm({ ...form, refreshRadarDaily: !form.refreshRadarDaily })} /><PolicyToggle icon={ShieldCheck} title="Dupla revisão" text={form.allowSelfApproval ? "Autoaprovação permitida para operação solo" : "Um segundo revisor é obrigatório"} active={!form.allowSelfApproval} onClick={() => setForm({ ...form, allowSelfApproval: !form.allowSelfApproval })} /></div>
        <div className="mt-6 flex flex-wrap gap-3"><Button type="submit" disabled={update.isPending} className="studio-light-button">{update.isPending ? <Loader2 className="studio-loader mr-2 h-4 w-4" /> : <CheckCircle2 className="mr-2 h-4 w-4" />}Salvar planejamento</Button><select className="studio-plan-select" value={planDays} onChange={event => setPlanDays(Number(event.target.value) as 7 | 15 | 30)}><option value={7}>Planejar 7 dias</option><option value={15}>Planejar 15 dias</option><option value={30}>Planejar 30 dias</option></select><Button type="button" disabled={generateCampaign.isPending} onClick={() => { const start = new Date(); start.setDate(start.getDate() + 1); generateCampaign.mutate({ idempotencyKey: crypto.randomUUID(), days: planDays, startDate: start, postsPerWeek: Number(form.postsPerWeek), defaultPublishTime: form.defaultPublishTime, objective: "Autoridade e atualidade", timezone: "America/Sao_Paulo" }); }} className="studio-new-entry">{generateCampaign.isPending ? <Loader2 className="studio-loader mr-2 h-4 w-4" /> : <WandSparkles className="mr-2 h-4 w-4" />}Gerar plano agora</Button></div>
        {planMessage && <div className="studio-feedback-message">{planMessage}<button type="button" onClick={() => setLocation("/calendario")}>Abrir calendário</button></div>}
      </form>
      <aside className="studio-automation-steps"><div className="studio-card-heading"><div><p className="studio-card-kicker">Fluxo protegido</p><h2>Da pauta à agenda</h2></div><Clock3 className="h-5 w-5 text-[#b98238]" /></div>{[{ icon: Radar, title: "1. Descobrir", text: "Radar consulta fontes oficiais quando acionado." }, { icon: WandSparkles, title: "2. Produzir", text: "IA prepara pauta, texto e direção visual vinculando a fonte." }, { icon: ShieldCheck, title: "3. Revisar", text: "Compliance e aprovação humana antecedem qualquer envio." }, { icon: CalendarRange, title: "4. Programar", text: "Conteúdo aprovado entra no calendário e na fila." }, { icon: Clock3, title: "5. Publicar", text: "A conexão oficial exige testes e confirmação expressa." }].map(({ icon: Icon, title, text }) => <div key={title} className="studio-step"><span><Icon className="h-4 w-4" /></span><div><strong>{title}</strong><p>{text}</p></div></div>)}</aside>
    </div>
    <AutopilotPanel />
  </div>;
}

function AutomationField({ label, full = false, children }: { label: string; full?: boolean; children: React.ReactNode }) { return <label className={full ? "studio-automation-field md:col-span-2" : "studio-automation-field"}><span>{label}</span>{children}</label>; }
function PolicyToggle({ icon: Icon, title, text, active = true, staticOn = false, onClick }: { icon: typeof ShieldCheck; title: string; text: string; active?: boolean; staticOn?: boolean; onClick?: () => void }) { const Card = onClick ? "button" : "div"; return <Card {...(onClick ? { type: "button" as const, onClick } : {})} className={`studio-policy-toggle ${onClick ? "is-clickable" : ""}`}><span className="studio-policy-icon"><Icon className="h-4 w-4" /></span><div><strong>{title}</strong><small>{text}</small></div><span className={`studio-policy-state ${active || staticOn ? "is-on" : ""}`} aria-label={active || staticOn ? "Ativado" : "Desativado"} /></Card>; }
