import { Button } from "@/components/ui/button";
import { CalendarClock, CheckCircle2, ExternalLink, Link2, Loader2, Plus, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { BrandProfile, ContentPost, contentSources } from "../../../drizzle/schema";

type ContentSource = typeof contentSources.$inferSelect;
type SourceInput = Pick<ContentSource, "title" | "sourceType" | "url" | "notes" | "verifiedAt">;
type BrandInput = Pick<BrandProfile, "brandName" | "segment" | "location" | "targetAudience" | "commercialGoal" | "toneOfVoice" | "primaryCta" | "prohibitedTerms" | "websiteUrl" | "whatsapp" | "visualGuidelines" | "operationMode">;

function dateTime(value?: Date | string | null) {
  if (!value) return "Sem data";
  return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}

export function CalendarPanel({ posts }: { posts: ContentPost[] }) {
  const items = useMemo(() => posts.filter(post => post.scheduledAt).sort((a, b) => new Date(a.scheduledAt ?? 0).getTime() - new Date(b.scheduledAt ?? 0).getTime()), [posts]);
  return <div className="space-y-6">
    <section className="saas-hero rounded-3xl p-6 sm:p-8"><div className="saas-eyebrow"><CalendarClock className="h-3.5 w-3.5" /> Calendário editorial</div><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white">Tudo que está previsto, em uma única fila temporal.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Rascunhos planejados aparecem com data-alvo; a publicação externa só ocorre após aprovação e preparação específica da rede.</p></section>
    <section className="saas-card overflow-hidden"><div className="grid grid-cols-[150px_1fr_130px_110px] gap-3 border-b border-white/[.06] px-5 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-slate-600"><span>Data</span><span>Conteúdo</span><span>Área</span><span>Status</span></div><div className="divide-y divide-white/[.05]">{items.length === 0 ? <p className="p-8 text-center text-sm text-slate-500">Nenhum conteúdo com data definida.</p> : items.map(post => <div key={post.id} className="grid grid-cols-[150px_1fr_130px_110px] gap-3 px-5 py-4 text-sm"><span className="text-xs text-[#e2ba7c]">{dateTime(post.scheduledAt)}</span><span className="min-w-0"><strong className="block truncate font-medium text-slate-200">{post.title}</strong><small className="mt-1 block text-[10px] text-slate-600">{post.format} · {post.campaign ?? "sem campanha"}</small></span><span className="text-xs text-slate-400">{post.area}</span><span className="text-xs text-slate-500">{post.status}</span></div>)}</div></section>
  </div>;
}

export function SourcesPanel({ sources, onAdd, adding }: { sources: ContentSource[]; onAdd: (value: SourceInput) => void; adding: boolean }) {
  const [form, setForm] = useState({ title: "", sourceType: "fonte oficial", url: "", notes: "", verifiedAt: "" });
  function submit(event: FormEvent) {
    event.preventDefault();
    onAdd({ title: form.title, sourceType: form.sourceType, url: form.url || null, notes: form.notes || null, verifiedAt: form.verifiedAt ? new Date(form.verifiedAt) : null });
    setForm({ title: "", sourceType: "fonte oficial", url: "", notes: "", verifiedAt: "" });
  }
  return <div className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]">
    <form onSubmit={submit} className="saas-card p-5 sm:p-6"><div className="saas-eyebrow"><Plus className="h-3.5 w-3.5" /> Nova fonte</div><h2 className="mt-3 text-xl font-semibold text-white">Cadastrar referência</h2><div className="mt-5 space-y-3"><input required className="editorial-input" placeholder="Título" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /><select className="editorial-input" value={form.sourceType} onChange={event => setForm({ ...form, sourceType: event.target.value })}><option>fonte oficial</option><option>legislação</option><option>jurisprudência</option><option>site institucional</option><option>doutrina</option></select><input type="url" className="editorial-input" placeholder="https://..." value={form.url} onChange={event => setForm({ ...form, url: event.target.value })} /><textarea className="editorial-input min-h-24 resize-y" placeholder="Observação" value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} /><input type="datetime-local" className="editorial-input" value={form.verifiedAt} onChange={event => setForm({ ...form, verifiedAt: event.target.value })} /><Button type="submit" disabled={adding} className="saas-button-primary w-full">{adding ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Link2 className="mr-2 h-4 w-4" />}Cadastrar fonte</Button></div></form>
    <section className="saas-card p-5 sm:p-6"><p className="saas-section-label">Rastreabilidade</p><h2 className="mt-2 text-2xl font-semibold text-white">Fontes cadastradas</h2><div className="mt-5 space-y-3">{sources.map(source => <article key={source.id} className="rounded-2xl border border-white/[.06] bg-white/[.02] p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-200">{source.title}</p><p className="mt-1 text-[10px] uppercase tracking-[.12em] text-[#e2ba7c]">{source.sourceType} · {source.verifiedAt ? "verificada" : "sem revisão registrada"}</p></div>{source.url && <a href={source.url} target="_blank" rel="noreferrer" className="text-slate-500 hover:text-white"><ExternalLink className="h-4 w-4" /></a>}</div>{source.notes && <p className="mt-3 text-xs leading-5 text-slate-500">{source.notes}</p>}</article>)}</div></section>
  </div>;
}

export function BrandPanel({ brand, onSave, saving }: { brand: BrandProfile | null; onSave: (value: BrandInput) => void; saving: boolean }) {
  const [form, setForm] = useState<BrandInput | null>(brand);
  useEffect(() => { if (brand) setForm(brand); }, [brand?.id]);
  if (!brand || !form) return null;
  return <form onSubmit={event => { event.preventDefault(); onSave({ brandName: form.brandName, segment: form.segment, location: form.location || null, targetAudience: form.targetAudience || null, commercialGoal: form.commercialGoal || null, toneOfVoice: form.toneOfVoice || null, primaryCta: form.primaryCta || null, prohibitedTerms: form.prohibitedTerms || null, websiteUrl: form.websiteUrl || null, whatsapp: form.whatsapp || null, visualGuidelines: form.visualGuidelines || null, operationMode: form.operationMode }); }} className="space-y-6">
    <section className="saas-hero rounded-3xl p-6 sm:p-8"><div className="saas-eyebrow"><ShieldCheck className="h-3.5 w-3.5" /> Brand OS</div><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white">Identidade, tom e limites da marca.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Estas diretrizes entram na geração de conteúdo e nos controles de compliance.</p></section>
    <section className="saas-card p-5 sm:p-6"><div className="grid gap-4 md:grid-cols-2"><Field label="Marca"><input className="editorial-input" value={form.brandName ?? ""} onChange={e => setForm({ ...form, brandName: e.target.value })} /></Field><Field label="Segmento"><input className="editorial-input" value={form.segment ?? ""} onChange={e => setForm({ ...form, segment: e.target.value })} /></Field><Field label="Localização"><input className="editorial-input" value={form.location ?? ""} onChange={e => setForm({ ...form, location: e.target.value })} /></Field><Field label="Website"><input type="url" className="editorial-input" value={form.websiteUrl ?? ""} onChange={e => setForm({ ...form, websiteUrl: e.target.value })} /></Field><Field label="Público-alvo"><textarea className="editorial-input min-h-24 resize-y" value={form.targetAudience ?? ""} onChange={e => setForm({ ...form, targetAudience: e.target.value })} /></Field><Field label="Objetivo comercial"><textarea className="editorial-input min-h-24 resize-y" value={form.commercialGoal ?? ""} onChange={e => setForm({ ...form, commercialGoal: e.target.value })} /></Field><Field label="Tom de voz"><textarea className="editorial-input min-h-28 resize-y" value={form.toneOfVoice ?? ""} onChange={e => setForm({ ...form, toneOfVoice: e.target.value })} /></Field><Field label="Diretrizes visuais"><textarea className="editorial-input min-h-28 resize-y" value={form.visualGuidelines ?? ""} onChange={e => setForm({ ...form, visualGuidelines: e.target.value })} /></Field><Field label="CTA institucional"><textarea className="editorial-input min-h-24 resize-y" value={form.primaryCta ?? ""} onChange={e => setForm({ ...form, primaryCta: e.target.value })} /></Field><Field label="Termos proibidos"><textarea className="editorial-input min-h-24 resize-y" value={form.prohibitedTerms ?? ""} onChange={e => setForm({ ...form, prohibitedTerms: e.target.value })} /></Field><Field label="WhatsApp"><input className="editorial-input" value={form.whatsapp ?? ""} onChange={e => setForm({ ...form, whatsapp: e.target.value })} /></Field><Field label="Modo operacional"><select className="editorial-input" value={form.operationMode ?? "manual"} onChange={e => setForm({ ...form, operationMode: e.target.value as BrandInput["operationMode"] })}><option value="manual">Manual</option><option value="semi_automatic">Semiautomático</option></select></Field></div><Button type="submit" disabled={saving} className="saas-button-primary mt-6">{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <CheckCircle2 className="mr-2 h-4 w-4" />}Salvar Brand OS</Button></section>
  </form>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</span>{children}</label>;
}
